{% set name = "apache-airflow-providers-snowflake" %}
{% set version = "2.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-snowflake-{{ version }}.tar.gz
  sha256: 5163a589317d4926dbb79e6493fe40177e77d85974d64113d101b33a5b8f6d49

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - apache-airflow >=2.1.0
    - snowflake-connector-python >=2.4.1,<2.7.2
    - snowflake-sqlalchemy >=1.1.0,!=1.2.5

test:
  imports:
    - airflow.providers.snowflake
    - airflow.providers.snowflake.example_dags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Snowflake for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-snowflake/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
